### ISSUE TITLE
no such table: auth_historicaluser when running Bitbucket Pipeline

### ISSUE THREAD

**Issue by StevenMapes** [treyhunner/django-simple-history#624]
**Update** After further testing the issue is due to a missing migrations relating to the Django Auth app that are not created within the project repository or contained within the django-simple-history app itself, and so a new step is required.

If you run a showmigrations locally you see the following:
```
admin
 [ ] 0001_initial
 [ ] 0002_logentry_remove_auto_add
 [ ] 0003_logentry_add_action_flag_choices
auth
 [ ] 0001_initial
 [ ] 0002_alter_permission_name_max_length
 [ ] 0003_alter_user_email_max_length
 [ ] 0004_alter_user_username_opts
 [ ] 0005_alter_user_last_login_null
 [ ] 0006_require_contenttypes_0002
 [ ] 0007_alter_validators_add_error_messages
 [ ] 0008_alter_user_username_max_length
 [ ] 0009_alter_user_last_name_max_length
 [ ] 0010_alter_group_name_max_length
 [ ] 0011_update_proxy_permissions
 [ ] 0012_historicaluser
```

When adding a showmigrations step on BitBucket Piplines. You'll see 

```
admin
 [ ] 0001_initial
 [ ] 0002_logentry_remove_auto_add
 [ ] 0003_logentry_add_action_flag_choices
auth
 [ ] 0001_initial
 [ ] 0002_alter_permission_name_max_length
 [ ] 0003_alter_user_email_max_length
 [ ] 0004_alter_user_username_opts
 [ ] 0005_alter_user_last_login_null
 [ ] 0006_require_contenttypes_0002
 [ ] 0007_alter_validators_add_error_messages
 [ ] 0008_alter_user_username_max_length
 [ ] 0009_alter_user_last_name_max_length
 [ ] 0010_alter_group_name_max_length
 [ ] 0011_update_proxy_permissions
```

This results in the unit tests failing due to the ```auth_historicaluser``` table not being created by the migrations.

**To Reproduce**
Steps to reproduce the behaviour:
1. Setup pipelines yml and push code to BitBucket
2. See error
 
**Fix**

The work around is to ensure that you add a step of ``python manage.py makemigrations auth`` into your YML file

E.G
```
pipelines:
  branches:
    'develop':
      - step:
          name: Python 3.7.3
          image: python:3.7.3
          caches:
            - pip
          script:
            - pip install -U pip setuptools
            - pip install -r requirements/pipelines.txt
            - python manage.py makemigrations auth
            - coverage erase
            - coverage run manage.py test
            - coverage report
```
